name: build-provenance

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    name: Publish package
    runs-on: windows-latest
    steps:
    - name: Build Provenance
      uses: bdehamer/abp@main
      with:
        subject-path: index.js
