---
name: publish

"on":
  workflow_dispatch:
    inputs:
      version:
        description: 'package version'
        required: true
        default: '1.0.1'
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - name: Bump package versions
        run: |
          sed -i "s/1.0.0/${{ github.event.inputs.version }}/" "package.json"
      - name: Publish package
        run: |
          npm install -g npm@next-11
          npm publish --provenance --access public --loglevel verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
