---
name: release

"on":
  release:

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Fail if github.ref is empty
        run: |
          if [ -z "${{ github.ref }}" ]; then
            echo "github.ref is empty"
            exit 1
          fi
